[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minecraft-bedrock-server-manager"
version = "0.1.0"
description = "Tool to manage a Minecraft server"
authors = [
    {name="Djayden-R"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = [
    "mcstatus",
    "github",
    "sys",
    "os",
    "subprocess",
    "urllib3",
    "psutil",
    "datetime",
    "dotenv",
    "requests",
    "enum"
]

[project.scripts]
minecraft-manager = "msm.cli:main"
